/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniForm;

import DAO.BanHangDao;
import DAO.CTHoaDonBHDao;
import DAO.HoaDonBHDao;
import DAO.monAnDao;
import HanhDong.hanhDongBanHang;
import Helper.ChuyenDoi;
import Helper.HanhDong;
import Helper.shareHelper;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ban;
import model.HoaDonBH;
import model.KhuVuc;
import model.MonAn;
import model.SuKien;

/**
 *
 * @author CHIEN
 */
public class ChiaCTHoaDonMni extends javax.swing.JFrame {

    DefaultTableModel modeTableBH;

    BanHangDao BHDao = new BanHangDao();
    HoaDonBHDao HDDAO = new HoaDonBHDao();
    CTHoaDonBHDao CTHDDAO = new CTHoaDonBHDao();
    monAnDao MONDAO = new monAnDao();

    SuKien SK = new SuKien();
    KhuVuc KV = new KhuVuc();
    Ban BanTachDen = new Ban();

    String MaHDcantach;

    /**
     * Creates new form ChiaCTHoaDonMni
     */
    public ChiaCTHoaDonMni(String MaHDCanTach, SuKien sk, KhuVuc kv, Ban banTachDen) {
        MaHDcantach = MaHDCanTach;
        BanTachDen = banTachDen;
        SK = sk;
        KV = kv;
        initComponents();
        setLocationRelativeTo(null);
        init();
    }

    void init() {
        loadDaTaToTableCTHoaDon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBanHang = new javax.swing.JTable();
        btnHuy = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(450, 700));
        setMinimumSize(new java.awt.Dimension(450, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 700));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(107, 70, 52));

        tblBanHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblBanHang.setForeground(new java.awt.Color(107, 70, 52));
        tblBanHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, "aaaa",  new Integer(2), "aaaa", "aaaa"},
                {null, null, "aaaa",  new Integer(2), "aaaa", "aaaa"},
                {null, null, "aaaa",  new Integer(2), "aaaa", "aaaa"},
                {null, null, "aaaa",  new Integer(2), "aaaa", null}
            },
            new String [] {
                "Stt", "Mã", "Tên món", "SL", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBanHang.setFillsViewportHeight(true);
        tblBanHang.setRowHeight(30);
        tblBanHang.setSelectionBackground(new java.awt.Color(107, 70, 52));
        tblBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBanHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBanHang);
        tblBanHang.getColumnModel().getColumn(0).setPreferredWidth(15);
        tblBanHang.getColumnModel().getColumn(1).setPreferredWidth(5);
        tblBanHang.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblBanHang.getColumnModel().getColumn(3).setPreferredWidth(10);

        btnHuy.setBackground(new java.awt.Color(204, 0, 0));
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/huy.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnXacNhan.setBackground(new java.awt.Color(126, 199, 47));
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dangNhap.png"))); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chia Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHuy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXacNhan)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnXacNhan))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBanHangMouseClicked
        // TODO add your handling code here:
        modeTableBH = (DefaultTableModel) tblBanHang.getModel();
        Integer index = tblBanHang.getSelectedRow();
        Integer soLuong = (Integer) modeTableBH.getValueAt(index, 3);
        if (evt.getClickCount() == 2) {
            String sl = JOptionPane.showInputDialog(tblBanHang, "Nhập Số Lượng", modeTableBH.getValueAt(index, 3));
            if (sl.length() == 0) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập");
            } else {
                try {
                    Integer SL = Integer.parseInt(sl);
                    if (SL > soLuong || SL < 0) {
                        JOptionPane.showMessageDialog(this, "Số lượng phải từ 0-" + soLuong);
                    } else {
                        modeTableBH.setValueAt(SL, index, 3);
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(tblBanHang, "Bạn phải nhập số nguyên");
                }
            }
        }
    }//GEN-LAST:event_tblBanHangMouseClicked
    public void loadDaTaToTableCTHoaDon() {
        modeTableBH = (DefaultTableModel) tblBanHang.getModel();
        CTHDDAO.loadDaTaToTableCTHD(HanhDong.MaHD, modeTableBH);
    }
    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed
    //
    public void taoHoaDonTamThoi() {
        System.out.println(HDDAO.getSoHD());
        KhuVuc kv = KV;
        SuKien sk = SK;

        HoaDonBH HDTamThoi = new HoaDonBH();
        HanhDong.MaHD = "HD0" + HDDAO.getSoHD();
        //tao mã hóa đơn
        HDTamThoi.setMaHD("HD0" + HDDAO.getSoHD());
        //lấy mã bàn
        HDTamThoi.setMaBan(BanTachDen.getMaBan());
        //lấy tên bàn
        HDTamThoi.setTenBan(BanTachDen.getTenBan());
        //lấy tên tài khoản
        HDTamThoi.setTenTaiKhoan(shareHelper.User.getTenTaiKhoan());
        //tổng tiền trên 1 hóa đơn chưa có km
        HDTamThoi.setTongTien(0);
        //lấy mã sự kiện
        HDTamThoi.setMaSuKien(sk.getMaSuKien());
        //lấy ưu đãi
        HDTamThoi.setUuDai(sk.getUuDai());
        //lấy tổng tiền thanh toán sau khi có km
        HDTamThoi.setTongTienThanhToan(0);
        //ghi chú là chưa thanh toán
        HDTamThoi.setGhiChu("Chưa Thanh Toán");

        HDDAO.insertHoaDon(HDTamThoi);

    }
    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        taoHoaDonTamThoi();
        modeTableBH = (DefaultTableModel) tblBanHang.getModel();
        for (int i = 0; i < modeTableBH.getRowCount(); i++) {
            Integer soLuong = (Integer) modeTableBH.getValueAt(i, 3);
            Integer maMon = (Integer) modeTableBH.getValueAt(i, 1);
            if (soLuong != 0) {
                MonAn mon = MONDAO.findByMaMon(maMon);
                CTHDDAO.updateSLCTHoaDonChia(MaHDcantach, maMon, String.valueOf(soLuong));
                CTHDDAO.insertCTHoaDon(HanhDong.MaHD, mon, soLuong);

            }
        }
        updateTrangThaiBan(BanTachDen.getMaBan());
        hanhDongBanHang.LoadBanToPanel();
        hanhDongBanHang.loadDaTaToTableCTHoaDon();
        this.dispose();
        
    }//GEN-LAST:event_btnXacNhanActionPerformed
    public void updateTrangThaiBan(Integer maBanGopVao) {
        BHDao.updateTrangThaiNgoiTheoMa(1, maBanGopVao);
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChiaCTHoaDonMni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChiaCTHoaDonMni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChiaCTHoaDonMni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChiaCTHoaDonMni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChiaCTHoaDonMni().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBanHang;
    // End of variables declaration//GEN-END:variables
}
