/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniForm;

import DAO.BanHangDao;
import DAO.CTHoaDonBHDao;
import DAO.HoaDonBHDao;
import HanhDong.hanhDongBanHang;
import Helper.ChuyenDoi;
import Helper.HanhDong;
import Helper.shareHelper;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ban;
import model.KhuVuc;
import model.SuKien;

/**
 *
 * @author CHIEN
 */
public class HoaDonTT extends javax.swing.JFrame {

    private String MaHD;
    private KhuVuc KhuVuc;
    private Ban Ban;
    private SuKien SuKien;

    BanHangDao BHDao = new BanHangDao();
    CTHoaDonBHDao CTHDDAO = new CTHoaDonBHDao();
    HoaDonBHDao HDDAO = new HoaDonBHDao();

    DefaultTableModel modeTableBH;

    /**
     * Creates new form HoaDonTT
     */
    public HoaDonTT(String maHd, KhuVuc kv, Ban ban, SuKien sk) {
        MaHD = maHd;
        KhuVuc = kv;
        Ban = ban;
        SuKien = sk;

        initComponents();
        setLocationRelativeTo(null);
        init();
    }

    void init() {
        modeTableBH = (DefaultTableModel) tblHoaDonTT.getModel();
        loadDaTaToTableCTHoaDon();
        //
        lbNhanVien.setText(shareHelper.User.getHoTen());
        lbTenKV.setText(KhuVuc.getTenKhuVuc());
        lbTenBan.setText(Ban.getTenBan());
        lbKM.setText(String.valueOf(SuKien.getUuDai()));
        lbThanhToan.setText(ChuyenDoi.chuyenDoiTien(HanhDong.TongTien - HanhDong.TongTien * SuKien.getUuDai() / 100));
    }

    public void loadDaTaToTableCTHoaDon() {
        CTHDDAO.loadDaTaToTableCTHD2(MaHD, modeTableBH);
        lbTongTien.setText(ChuyenDoi.chuyenDoiTien(HanhDong.TongTien));
        lbMaHD.setText(HanhDong.MaHD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDonTT = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbMaHD = new javax.swing.JLabel();
        lbTenKV = new javax.swing.JLabel();
        lbTenBan = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        lbKM = new javax.swing.JLabel();
        lbThanhToan = new javax.swing.JLabel();
        lbKM1 = new javax.swing.JLabel();
        lbTongTien1 = new javax.swing.JLabel();
        lbTongTien2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbTenBan1 = new javax.swing.JLabel();
        lbNhanVien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(212, 181, 152));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(490, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(490, 800));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 70, 52));
        jLabel1.setText("Mã HD:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(107, 70, 52));
        jLabel2.setText("BiTies");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(107, 70, 52));
        jLabel3.setText("Phiếu thanh toán");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(107, 70, 52));
        jLabel4.setText("Số 1 Trịnh Văn Bô, Nam Từ Liêm, Hà Nội");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(107, 70, 52));
        jLabel5.setText("Khu vực:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(107, 70, 52));
        jLabel6.setText("Bàn:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        tblHoaDonTT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblHoaDonTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "aaaa",  new Integer(2), "aaaa", "aaaa"},
                {null, "aaaa",  new Integer(2), "aaaa", "aaaa"},
                {null, "aaaa",  new Integer(2), "aaaa", "aaaa"},
                {null, "aaaa",  new Integer(2), "aaaa", null}
            },
            new String [] {
                "Stt", "Tên món", "SL", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDonTT.setEnabled(false);
        tblHoaDonTT.setFillsViewportHeight(true);
        tblHoaDonTT.setRowHeight(30);
        jScrollPane1.setViewportView(tblHoaDonTT);
        tblHoaDonTT.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblHoaDonTT.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblHoaDonTT.getColumnModel().getColumn(2).setPreferredWidth(5);
        //tblHoaDonTT.getColumnModel().getColumn(2).setPreferredWidth(20);
        //tblHoaDonTT.getColumnModel().getColumn(3).setPreferredWidth(20);

        jPanel2.add(jScrollPane1);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(107, 70, 52));
        jLabel11.setText("Kính chào quý khách và hẹn gặp lại");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(107, 70, 52));
        jLabel12.setText("Thanh toán:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thoat.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        lbMaHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbMaHD.setForeground(new java.awt.Color(107, 70, 52));
        lbMaHD.setText(".......................");

        lbTenKV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTenKV.setForeground(new java.awt.Color(107, 70, 52));
        lbTenKV.setText("......................");

        lbTenBan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTenBan.setForeground(new java.awt.Color(107, 70, 52));
        lbTenBan.setText("........................");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(107, 70, 52));
        jLabel13.setText("Tổng tiền:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(107, 70, 52));
        jLabel14.setText("Khuyến mại:");

        lbTongTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTongTien.setForeground(new java.awt.Color(107, 70, 52));
        lbTongTien.setText(".......................");

        lbKM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbKM.setForeground(new java.awt.Color(107, 70, 52));
        lbKM.setText("......................");

        lbThanhToan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbThanhToan.setForeground(new java.awt.Color(107, 70, 52));
        lbThanhToan.setText("......................");

        lbKM1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbKM1.setForeground(new java.awt.Color(107, 70, 52));
        lbKM1.setText("%");

        lbTongTien1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTongTien1.setForeground(new java.awt.Color(107, 70, 52));
        lbTongTien1.setText("VND");

        lbTongTien2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTongTien2.setForeground(new java.awt.Color(107, 70, 52));
        lbTongTien2.setText("VND");

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Xác nhận thanh toán");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbTenBan1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTenBan1.setForeground(new java.awt.Color(107, 70, 52));
        lbTenBan1.setText("Nhân viên:");

        lbNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNhanVien.setForeground(new java.awt.Color(107, 70, 52));
        lbNhanVien.setText("........................");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbTenKV, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbTenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbKM)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbKM1))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbTongTien)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbTongTien1))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbThanhToan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbTongTien2))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbTenBan1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(170, 170, 170)))
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbMaHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbTenKV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbTenBan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenBan1)
                    .addComponent(lbNhanVien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTongTien)
                            .addComponent(lbTongTien1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbKM)
                            .addComponent(lbKM1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbThanhToan)
                            .addComponent(lbTongTien2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            double tt = HanhDong.TongTien - HanhDong.TongTien * SuKien.getUuDai() / 100;
            HDDAO.thanhToanHoaDon(shareHelper.User.getTenTaiKhoan(), HanhDong.TongTien,
                    SuKien.getMaSuKien(), SuKien.getUuDai(), tt, MaHD);
            BHDao.updateTrangThaiNgoiTheoMa(0, Ban.getMaBan());
            JOptionPane.showMessageDialog(this, "Thanh toán thành công");
            hanhDongBanHang.LoadBanToPanel();
            HanhDong.MaHD = null;
            hanhDongBanHang.loadDaTaToTableCTHoaDon();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi thanh toán");
            e.printStackTrace();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HoaDonTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HoaDonTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HoaDonTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HoaDonTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HoaDonTT().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbKM;
    private javax.swing.JLabel lbKM1;
    private javax.swing.JLabel lbMaHD;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JLabel lbTenBan;
    private javax.swing.JLabel lbTenBan1;
    private javax.swing.JLabel lbTenKV;
    private javax.swing.JLabel lbThanhToan;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JLabel lbTongTien1;
    private javax.swing.JLabel lbTongTien2;
    private javax.swing.JTable tblHoaDonTT;
    // End of variables declaration//GEN-END:variables
}
