/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniForm;

import DAO.CTHoaDonBHDao;
import Helper.ChuyenDoi;
import Helper.HanhDong;
import java.awt.Component;
import java.awt.Image;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MonAn;

/**
 *
 * @author CHIEN
 */
public class MonAnBH extends javax.swing.JPanel {

    MonAn monAn = new MonAn();
    Integer SL = 0;

    CTHoaDonBHDao CTHDDaoM = new CTHoaDonBHDao();
    DefaultTableModel Mode;
    /**
     * Creates new form MonAnBH
     */
    public MonAnBH(MonAn mon, DefaultTableModel mode) {
        initComponents();
        monAn = mon;
        Mode = mode;
        init();
    }

    void init() {
        ImageIcon img = new ImageIcon("src\\ImageSP\\" + monAn.getHinhAnh());
        Image im = img.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(300, 200, im.SCALE_SMOOTH));
        lbAnhMon.setIcon(icon);

        lbTenMon.setText(monAn.getTenMon());
        lbGiaTien.setText(ChuyenDoi.chuyenDoiTien(monAn.getDonGia()));
        lbMaMon.setText(String.valueOf(monAn.getMaMon()));
    }

    //
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbAnhMon = new javax.swing.JLabel();
        lbTenMon = new javax.swing.JLabel();
        lbGiaTien = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbMaMon = new javax.swing.JLabel();
        lbMaMon1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(300, 338));
        setPreferredSize(new java.awt.Dimension(300, 338));
        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 338));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 338));

        lbAnhMon.setMaximumSize(new java.awt.Dimension(300, 200));
        lbAnhMon.setMinimumSize(new java.awt.Dimension(300, 200));
        lbAnhMon.setPreferredSize(new java.awt.Dimension(300, 200));

        lbTenMon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTenMon.setForeground(new java.awt.Color(255, 255, 255));
        lbTenMon.setText("Tên Món");

        lbGiaTien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbGiaTien.setForeground(new java.awt.Color(255, 255, 255));
        lbGiaTien.setText("Giá Tiền");

        jButton1.setBackground(new java.awt.Color(107, 70, 52));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbMaMon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMaMon.setForeground(new java.awt.Color(255, 255, 255));
        lbMaMon.setText("Mã Món");

        lbMaMon1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMaMon1.setForeground(new java.awt.Color(255, 255, 255));
        lbMaMon1.setText("VND");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbGiaTien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMaMon1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbMaMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addComponent(lbAnhMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbAnhMon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaMon1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sl = JOptionPane.showInputDialog("Mời nhập số lượng");

        System.out.println(sl);
        if (sl != null) {
            try {
                SL = Integer.parseInt(sl);

            } catch (Exception e) {
                Component cpn = null;
                JOptionPane.showMessageDialog(cpn, "Bạn phải nhập số nguyên");
            }
            if (SL != 0) {
                try {
                    CTHDDaoM.insertCTHoaDon(HanhDong.MaHD, monAn, SL);
                    CTHDDaoM.loadDaTaToTableCTHD(HanhDong.MaHD, Mode);
                    HanhDong.LBTongTien.setText(ChuyenDoi.chuyenDoiTien(HanhDong.TongTien));
                } catch (Exception e) {
                    Component cpn = null;
                    JOptionPane.showMessageDialog(cpn, "Món đã tồn tại trong menu");
                    //e.printStackTrace();
                }
            }
        } else {

        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAnhMon;
    private javax.swing.JLabel lbGiaTien;
    private javax.swing.JLabel lbMaMon;
    private javax.swing.JLabel lbMaMon1;
    private javax.swing.JLabel lbTenMon;
    // End of variables declaration//GEN-END:variables
}
